# Generated by Django 2.1.5 on 2019-01-08 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedExaminationSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_01', models.TextField()),
                ('answer_01_points_earned', models.IntegerField()),
                ('answer_02', models.TextField()),
                ('answer_02_points_earned', models.IntegerField()),
                ('answer_03', models.TextField()),
                ('answer_03_points_earned', models.IntegerField()),
                ('answer_04', models.TextField()),
                ('answer_04_points_earned', models.IntegerField()),
                ('answer_05', models.TextField()),
                ('answer_05_points_earned', models.IntegerField()),
                ('average_score', models.FloatField()),
                ('final_rating', models.IntegerField()),
                ('is_checked', models.BooleanField(default=False)),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_sheet_title', models.CharField(max_length=50)),
                ('task_01_title', models.CharField(max_length=50)),
                ('task_01_description', models.TextField()),
                ('task_01_max_points', models.IntegerField()),
                ('task_02_title', models.CharField(max_length=50)),
                ('task_02_description', models.TextField()),
                ('task_02_max_points', models.IntegerField()),
                ('task_03_title', models.CharField(max_length=50)),
                ('task_03_description', models.TextField()),
                ('task_03_max_points', models.IntegerField()),
                ('task_04_title', models.CharField(max_length=50)),
                ('task_04_description', models.TextField()),
                ('task_04_max_points', models.IntegerField()),
                ('task_05_title', models.CharField(max_length=50)),
                ('task_05_description', models.TextField()),
                ('task_05_max_points', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
