# Generated by Django 2.1.5 on 2019-01-09 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0002_auto_20190108_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexaminationsheet',
            name='checked_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='completedexaminationsheet',
            name='completed_examination_sheet_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
