# Generated by Django 2.1.5 on 2019-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0003_auto_20190109_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_01_points_earned',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_02_points_earned',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_03_points_earned',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_04_points_earned',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_05_points_earned',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='average_score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='checked_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='final_rating',
            field=models.IntegerField(blank=True),
        ),
    ]
