# Generated by Django 2.1.5 on 2019-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0004_auto_20190110_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_01_points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_02_points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_03_points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_04_points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='answer_05_points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedexaminationsheet',
            name='final_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
